#!/usr/bin/env python3
"""Generate deterministic NetNTLMv1 hashes for the lookup benchmark.

Algorithm mirrors cpu_rt_functions.c::netntlmv1_hash in this repo:

    1. Generate a 7-byte plaintext from a seeded PRNG (byte charset 0..255).
    2. Expand it to an 8-byte DES key via setup_des_key (bit-spread, LSBs
       cleared as parity-bit territory).
    3. DES-ECB encrypt the magic value 1122334455667788 with that key.
    4. The 8-byte ciphertext (16 hex chars) is the "hash" stored in the
       rainbow table.

Both blurbdust/master and feature/faster-table-loading use this exact same
simplified NetNTLMv1 scheme (challenge hardcoded to 1122334455667788), so
hashes generated by this tool are valid inputs for either branch.

Usage:
    gen_netntlmv1_hashes.py --seed N --count N --out path
"""
import argparse
import random
import sys

try:
    from Crypto.Cipher import DES
except ImportError:
    print(
        "ERROR: pycryptodome not installed. "
        "Install it (or run inside the bench venv): "
        "pip install pycryptodome",
        file=sys.stderr,
    )
    sys.exit(2)


MAGIC = bytes.fromhex("1122334455667788")


def setup_des_key(seven: bytes) -> bytes:
    """Expand 7 input bytes to an 8-byte DES key.

    Mirrors setup_des_key() in cpu_rt_functions.c lines 347-354. The 56 bits
    of input are spread across the high 7 bits of each output byte; the low
    bit of each output byte is left zero (parity territory).
    """
    if len(seven) != 7:
        raise ValueError(f"setup_des_key requires 7 bytes, got {len(seven)}")
    k = seven
    out = bytearray(8)
    out[0] = (((k[0] >> 1) & 0x7f) << 1) & 0xff
    out[1] = (((k[0] & 0x01) << 6 | ((k[1] >> 2) & 0x3f)) << 1) & 0xff
    out[2] = (((k[1] & 0x03) << 5 | ((k[2] >> 3) & 0x1f)) << 1) & 0xff
    out[3] = (((k[2] & 0x07) << 4 | ((k[3] >> 4) & 0x0f)) << 1) & 0xff
    out[4] = (((k[3] & 0x0f) << 3 | ((k[4] >> 5) & 0x07)) << 1) & 0xff
    out[5] = (((k[4] & 0x1f) << 2 | ((k[5] >> 6) & 0x03)) << 1) & 0xff
    out[6] = (((k[5] & 0x3f) << 1 | ((k[6] >> 7) & 0x01)) << 1) & 0xff
    out[7] = ((k[6] & 0x7f) << 1) & 0xff
    return bytes(out)


def netntlmv1_hash(plaintext_seven: bytes) -> bytes:
    """Compute the 8-byte NetNTLMv1 hash for a 7-byte plaintext."""
    key = setup_des_key(plaintext_seven)
    cipher = DES.new(key, DES.MODE_ECB)
    return cipher.encrypt(MAGIC)


def generate(seed: int, count: int, out_path: str) -> None:
    """Write `count` hashes to `out_path` and plaintexts to `<out>.plaintexts`."""
    rng = random.Random(seed)
    sidecar_path = out_path + ".plaintexts"
    with open(out_path, "w") as out_f, open(sidecar_path, "w") as side_f:
        for _ in range(count):
            plaintext = bytes(rng.randrange(256) for _ in range(7))
            h = netntlmv1_hash(plaintext)
            out_f.write(h.hex() + "\n")
            side_f.write(f"{h.hex()}:{plaintext.hex()}\n")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--seed", type=int, required=True, help="PRNG seed")
    p.add_argument("--count", type=int, required=True, help="Number of hashes to emit")
    p.add_argument("--out", required=True, help="Output file path")
    args = p.parse_args()
    generate(args.seed, args.count, args.out)
    print(f"Wrote {args.count} NetNTLMv1 hashes to {args.out}")
    print(f"Plaintexts (sanity sidecar): {args.out}.plaintexts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
